---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-cd-pipeline-sa # service account to be used during pipeline run
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: github-api-token
  namespace: default
type: Opaque
stringData:
  token: ""
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: sample-cd-pipeline-trigger-template
  namespace: default
spec:
  params:
    - name: chart-version
    - name: git-url
    - name: git-full-name
    - name: release-directory
    - name: release-file
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: sample-cd-pipeline-run- # create unique name automatically
      spec:
        serviceAccountName: sample-cd-pipeline-sa
        pipelineRef:
          name: sample-cd-pipeline
        params:
          - name: chart-version
            value: $(tt.params.chart-version)
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-full-name
            value: $(tt.params.git-full-name)
          - name: release-directory
            value: $(tt.params.release-directory)
          - name: release-file
            value: $(tt.params.release-file)
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: sample-cd-pipeline-trigger-binding
  namespace: default
spec:
  params:
    - name: chart-version
      value: $(body.metadata.revision)
