---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: sample-cd-environment-promotion
  namespace: default
spec:
  type: generic
  address: http://el-sample-cd-event-listener.default.svc:8080 # Tekton Event Listener serivce url
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: sample-app-event-alerts
  namespace: default
spec:
  providerRef: 
    name: sample-cd-environment-promotion
  eventSeverity: info
  eventSources:
    #
    # the dev and staging environments are configured to look deploy new helm versions
    # automatically based on semver range patterns. for prod we want to use a specific
    # version and we want to update it ONLY if the staging release was successful.
    # 
    # this will trigger an alert on changes to the demo HelmRelease object in the
    # staging environment (namespace)
    # 
    - kind: HelmRelease
      namespace: staging
      name: demo
  exclusionList:  # filter out intermediary events that should not trigger a pipeline run
    - ".*upgrade.*has.*started"
    - ".*not.*ready"
    - "^Dependencies.*"
