---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-cd-pipeline-sa # service account to be used during pipeline run
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: github-api-token
  namespace: default
type: Opaque
stringData:
  token: ""
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: sample-cd-pipeline-trigger-template
  namespace: default
spec:
  params:
    - name: revision
    - name: source-git-url
    - name: source-git-directory
    - name: destination-git-url
    - name: destination-git-full-name
    - name: destination-git-directory
    - name: promotion-namespace
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: sample-cd-pipeline-run- # create unique name automatically
      spec:
        serviceAccountName: sample-cd-pipeline-sa
        pipelineRef:
          name: sample-cd-pipeline
        params:
          - name: revision
            value: $(tt.params.revision)
          - name: source-git-url
            value: $(tt.params.source-git-url)
          - name: source-git-directory
            value: $(tt.params.source-git-directory)
          - name: destination-git-url
            value: $(tt.params.destination-git-url)
          - name: destination-git-full-name
            value: $(tt.params.destination-git-full-name)
          - name: destination-git-directory
            value: $(tt.params.destination-git-directory)
          - name: promotion-namespace
            value: $(tt.params.promotion-namespace)
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: sample-cd-pipeline-trigger-binding
  namespace: default
spec:
  params:
    - name: git-url
      value: <REPLACE ME>
    - name: git-full-name
      value: <REPLACE ME>
    - name: chart-version
      value: $(body.metadata.revision)
