apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.38.3/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.20.2/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.20.2/interceptors.yaml
