apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-ci-pipeline
  namespace: default
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: image-name
      type: string
    - name: chart-path
      type: string
    - name: tag
      type: string
      default: latest
    - name: path-to-image-context
      type: string
      default: ./
    - name: path-to-dockerfile
      type: string
      default: ./Dockerfile
    - name: gh-pages-branch
      type: string
      default: gh-pages
  workspaces:
    - name: shared-data
    - name: docker-credentials
  tasks:
    - name: clone-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared-data
          subPath: source # keep source data separate from rest of data
    - name: clone-gh-pages
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.gh-pages-branch)
      workspaces:
        - name: output
          workspace: shared-data
          subPath: gh-pages # keep gh-pages data separate from rest of data
    - name: build-image
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.image-name):$(params.tag)
        - name: CONTEXT
          value: $(params.path-to-image-context)
        - name: DOCKERFILE
          value: $(params.path-to-dockerfile)
      runAfter: # ensures tasks run in correct order
        - clone-source
      workspaces:
        - name: source
          workspace: shared-data
          subPath: source
        - name: dockerconfig
          workspace: docker-credentials
    - name: helm-release
      taskRef:
        name: helm-release
      params:
        - name: chart-path
          value: $(params.chart-path)
        - name: version
          value: $(params.tag)
        - name: repo-url
          value: $(params.git-url)
      runAfter:
        - build-image
      workspaces:
        - name: source
          workspace: shared-data
          subPath: source
        - name: gh-pages
          workspace: shared-data
          subPath: gh-pages
