---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: sample-chart
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: weavegitops-tekton-demo
      interval: 1m
