apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yq
  namespace: default
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: yq command arguments
      type: array
  steps:
    - name: yq
      image: mikefarah/yq:4
      securityContext:
        runAsUser: 0 # needed for proper workspace access
      workingDir: $(workspaces.source.path)
      command: ["yq"]
      args: ["$(params.args[*])"]
