apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo
  namespace: staging
spec:
  interval: 1m
  chart:
    spec:
      chart: sample-chart
      version: ">=0.0.0" # deploy latest released version
      sourceRef:
        kind: HelmRepository
        name: tekton-demo
      interval: 1m
  values:
    image:
      repository: ${image_name} # replaced by flux using post build substitution
