---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo
  namespace: staging
spec:
  interval: 5m
  chart:
    spec:
      chart: sample-chart
      version: ">=0.0.0" # deploy latest release
      sourceRef:
        kind: HelmRepository
        name: weavegitops-tekton-demo
      interval: 1m
