apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo
  namespace: prod
spec:
  interval: 5m
  chart:
    spec:
      chart: sample-chart
      version: "0.0.1" # deploy specific version
      sourceRef:
        kind: HelmRepository
        name: tekton-demo
      interval: 1m
