apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tekton-demo
  namespace: prod
spec:
  interval: 1m
  url: ${gh_pages_url} # replaced by flux using post build substitution
